name: dragons

services:
  app:
    image: dragons
    build:
      context: .
      target: app
    ports:
      - '3000:3000'

  bot:
    profiles: [bot]
    image: dragons
    build:
      context: .
      target: app
    command: node dist/cli/play.js
