export const fixtures = {
  start: {
    gameId: '0BzjArhx',
    lives: 3,
    gold: 0,
    level: 0,
    score: 0,
    highScore: 0,
    turn: 0,
  },
  plainAd: {
    adId: 'cx6vhNAH',
    message: 'Help Otar Crawford to fix their weed',
    reward: 8,
    expiresIn: 5,
    encrypted: null,
    probability: 'Sure thing',
  },
  base64Ad: {
    adId: 'ZlV6NUs2QlM=',
    message:
      'SW5maWx0cmF0ZSBUaGUgSXZvcnkgQWxsaWdhdG9yIEdhbmcgYW5kIHJlY292ZXIgdGhlaXIgc2VjcmV0cy4=',
    reward: 153,
    expiresIn: 2,
    encrypted: 1,
    probability: 'UGxheWluZyB3aXRoIGZpcmU=',
  },
  rot13Ad: {
    adId: 'pk6iuANU',
    message: 'Uryc Bgne Penjsbeq gb svk gurve jrrq',
    reward: 8,
    expiresIn: 5,
    encrypted: 2,
    probability: 'Fher guvat',
  },
  shop: [
    { id: 'hpot', name: 'Healing potion', cost: 50 },
    { id: 'cs', name: 'Claw Sharpening', cost: 100 },
    { id: 'gas', name: 'Gasoline', cost: 100 },
    { id: 'wax', name: 'Copper Plating', cost: 100 },
    { id: 'tricks', name: 'Book of Tricks', cost: 100 },
    { id: 'wingpot', name: 'Potion of Stronger Wings', cost: 100 },
    { id: 'ch', name: 'Claw Honing', cost: 300 },
    { id: 'rf', name: 'Rocket Fuel', cost: 300 },
    { id: 'iron', name: 'Iron Plating', cost: 300 },
    { id: 'mtrix', name: 'Book of Megatricks', cost: 300 },
    { id: 'wingpotmax', name: 'Potion of Awesome Wings', cost: 300 },
  ],
  solved: {
    success: true,
    lives: 3,
    gold: 8,
    score: 8,
    highScore: 0,
    turn: 3,
    message: 'You successfully solved the mission!',
  },
  failed: {
    success: false,
    lives: 3,
    gold: 45,
    score: 95,
    highScore: 0,
    turn: 7,
    message: 'You failed on the mission!',
  },
  bought: { shoppingSuccess: true, gold: 29, lives: 4, level: 0, turn: 5 },
  notBought: { shoppingSuccess: false, gold: 0, lives: 3, level: 0, turn: 1 },
  reputation: { people: 0, state: 0, underworld: 0 },
} as const;
